import requests
import random
import time
import logging
from typing import List

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler("chatbot.log"),
        logging.StreamHandler()
    ]
)

# Configuration
BASE_URL = "https://chemistry.gaia.domains"
MODEL = "qwen2-0.5b-instruct"
MAX_RETRIES = 100  # Essentially infinite retries
RETRY_DELAY = 5  # Seconds between retries
QUESTION_DELAY = 1  # Seconds between successful questions

QUESTIONS = [
    "What is no-code?", 
"How will AI shape the future of mental health?",
"How can AI be made more reliable for disaster response?",
"How is AI transforming customer experience?",
"How is AI transforming sports analytics?",
"What are the limitations of AI in supply chain?",
"What role does AI play in supply chain today?",
"How does AI compare to traditional methods in criminal justice?",
"What are the latest advancements in AI for human augmentation?",
"How can AI be made more reliable for predictive analytics?",
"What are some misconceptions about AI in education accessibility?",
"What are the limitations of AI in ethics?",
"What are some misconceptions about AI in energy efficiency?",
"What are the limitations of AI in elderly care?",
"What challenges do researchers face when applying AI to disaster response?",
"What risks should we consider when using AI in creativity?",
"How is AI transforming gaming?",
"How is AI transforming finance?",
"How does AI affect employment in financial fraud detection?",
"How does AI compare to traditional methods in education accessibility?",
"How can AI enhance productivity in data privacy?",
"What challenges do researchers face when applying AI to creativity?",
"How can AI be made more reliable for space exploration?",
"What risks should we consider when using AI in sports analytics?",
"How can AI be used to solve problems in self-driving cars?",
"What are the long-term implications of AI on manufacturing?",
"How do biases in AI models affect human augmentation?",
"How will AI shape the future of scientific research?",
"What ethical dilemmas arise from AI in customer experience?",
"What are some misconceptions about AI in space exploration?",
"How does AI compare to traditional methods in agriculture?",
"What role does AI play in robotics today?",
"What role does AI play in biotechnology today?",
"What risks should we consider when using AI in customer experience?",
"How does AI interact with other technologies in marketing?",
"What risks should we consider when using AI in smart cities?",
"What innovations in AI could revolutionize marketing?",
"How does AI impact human decision-making in financial fraud detection?",
"How will AI shape the future of social media?",
"What are the latest advancements in AI for cybersecurity?",
"How does AI interact with other technologies in future jobs?",
"What ethical dilemmas arise from AI in drug discovery?",
"What are the limitations of AI in scientific research?",
"How does AI compare to traditional methods in future jobs?",
"What are the benefits and drawbacks of AI in music composition?",
"How does AI compare to traditional methods in public policy?",
"What are the latest advancements in AI for education?",
"How is AI transforming marketing?",
"How can AI be made more reliable for music composition?",
"How can AI enhance productivity in augmented reality?",
"How can AI be made more reliable for autonomous systems?",
"What are the latest advancements in AI for social media?",
"What challenges do researchers face when applying AI to education?",
"How can AI be used to solve problems in blockchain?",
"What innovations in AI could revolutionize criminal justice?",
"What ethical dilemmas arise from AI in retail?",
"How is AI transforming personal assistants?",
"What are the benefits and drawbacks of AI in transportation?",
"How does AI interact with other technologies in virtual reality?",
"What ethical dilemmas arise from AI in self-driving cars?",
"What are the latest advancements in AI for autonomous systems?",
"How is AI transforming manufacturing?",
"What are the latest advancements in AI for self-driving cars?",
"How can AI be made more reliable for personal assistants?",
"How do biases in AI models affect gaming?",
"What are the limitations of AI in customer service?",
"How can AI be made more reliable for blockchain?",
"What are the latest advancements in AI for mental health?",
"How does AI affect employment in biotechnology?",
"How can AI be made more reliable for self-driving cars?",
"How does AI interact with other technologies in autonomous systems?",
"What are some misconceptions about AI in human augmentation?",
"How do biases in AI models affect criminal justice?",
"What innovations in AI could revolutionize customer experience?",
"What challenges do researchers face when applying AI to biotechnology?",
"How does AI compare to traditional methods in creativity?",
"What risks should we consider when using AI in news generation?",
"How will AI shape the future of self-driving cars?",
"What are the long-term implications of AI on artificial creativity?",
"How will AI shape the future of education accessibility?",
"How can AI be used to solve problems in supply chain?",
"How does AI compare to traditional methods in robotics?",
"How does AI affect employment in robotics?",
"How can AI be made more reliable for financial fraud detection?",
"What challenges do researchers face when applying AI to finance?",
"How can AI be made more reliable for data privacy?",
"What are the latest advancements in AI for customer service?",
"How does AI impact human decision-making in artificial creativity?",
"How does AI interact with other technologies in agriculture?",
"What are the benefits and drawbacks of AI in cybersecurity?",
"What are the latest advancements in AI for drug discovery?",
"What risks should we consider when using AI in elderly care?",
"What are the limitations of AI in future jobs?",
"What ethical dilemmas arise from AI in smart cities?",
"What are the long-term implications of AI on language processing?",
"How is AI transforming ethics?",
"How can AI enhance productivity in customer experience?",
"What risks should we consider when using AI in social media?",
"What role does AI play in data privacy today?",
"What ethical dilemmas arise from AI in data privacy?",
"What ethical dilemmas arise from AI in creativity?",
"What are the long-term implications of AI on music composition?",
"What risks should we consider when using AI in criminal justice?",
"What are the long-term implications of AI on human augmentation?",
"What innovations in AI could revolutionize space exploration?",
"What risks should we consider when using AI in manufacturing?",
"How will AI shape the future of criminal justice?",
"What challenges do researchers face when applying AI to ethics?",
"What challenges do researchers face when applying AI to supply chain?",
"What challenges do researchers face when applying AI to self-driving cars?",
"What are the latest advancements in AI for predictive analytics?",
"What challenges do researchers face when applying AI to virtual reality?",
"How does AI interact with other technologies in space exploration?",
"What are some misconceptions about AI in sports analytics?",
"How can AI be used to solve problems in social media?",
"What role does AI play in climate change today?",
"How is AI transforming self-driving cars?",
"What are the long-term implications of AI on news generation?",
"How can AI be used to solve problems in customer service?",
"How does AI impact human decision-making in manufacturing?",
"What are the benefits and drawbacks of AI in robotics?",
"How does AI compare to traditional methods in manufacturing?",
"How does AI impact human decision-making in scientific research?",
"How does AI interact with other technologies in healthcare?",
"How can AI be made more reliable for criminal justice?",
"How can AI be made more reliable for drug discovery?",
"What are the latest advancements in AI for public policy?",
"How is AI transforming artificial creativity?",
"What challenges do researchers face when applying AI to education accessibility?",
"How is AI transforming elderly care?",
"What innovations in AI could revolutionize biotechnology?",
"What are some misconceptions about AI in entertainment?",
"How can AI be used to solve problems in education?",
"How is AI transforming robotics?",
"How can AI be used to solve problems in virtual reality?",
"How can AI enhance productivity in education?",
"How does AI affect employment in climate change?",
"How do biases in AI models affect cybersecurity?",
"How does AI interact with other technologies in climate change?",
"How can AI enhance productivity in drug discovery?",
"How can AI enhance productivity in artificial creativity?",
"How does AI affect employment in business strategy?",
"What are the limitations of AI in self-driving cars?",
"How is AI transforming scientific research?",
"How does AI affect employment in music composition?",
"What are some misconceptions about AI in law enforcement?",
"What challenges do researchers face when applying AI to personal assistants?",
"What are the latest advancements in AI for transportation?",
"What are the long-term implications of AI on transportation?",
"How do biases in AI models affect mental health?",
"How do biases in AI models affect financial fraud detection?",
"What are some misconceptions about AI in scientific research?",
"How will AI shape the future of marketing?",
"What are the latest advancements in AI for retail?",
"How can AI be made more reliable for supply chain?",
"How do biases in AI models affect news generation?",
"How does AI interact with other technologies in entertainment?",
"How do biases in AI models affect entertainment?",
"How is AI transforming education accessibility?",
"How can AI be used to solve problems in military?",
"What ethical dilemmas arise from AI in law enforcement?",
"What role does AI play in law enforcement today?",
"What are some misconceptions about AI in disaster response?",
"How does AI interact with other technologies in supply chain?",
"What are some misconceptions about AI in data privacy?",
"How does AI affect employment in education accessibility?",
"How does AI affect employment in future jobs?",
"What risks should we consider when using AI in artificial creativity?",
"What are the long-term implications of AI on elderly care?",
"What are the benefits and drawbacks of AI in marketing?",
"What ethical dilemmas arise from AI in public policy?",
"What are the benefits and drawbacks of AI in public policy?",
"What ethical dilemmas arise from AI in music composition?",
"How will AI shape the future of supply chain?",
"How does AI impact human decision-making in disaster response?",
"How do biases in AI models affect retail?",
"How do biases in AI models affect blockchain?",
"What innovations in AI could revolutionize energy efficiency?",
"How does AI affect employment in autonomous systems?",
"How can AI enhance productivity in retail?",
"What risks should we consider when using AI in customer service?",
"What are the latest advancements in AI for military?",
"What are the benefits and drawbacks of AI in energy efficiency?",
"What are the limitations of AI in transportation?",
"How will AI shape the future of news generation?",
"What challenges do researchers face when applying AI to language processing?",
"How does AI compare to traditional methods in supply chain?",
"What challenges do researchers face when applying AI to law enforcement?",
"How can AI enhance productivity in human augmentation?",
"What are the latest advancements in AI for climate change?",
"What are the limitations of AI in climate change?",
"How is AI transforming entertainment?",
"How can AI enhance productivity in agriculture?",
"What risks should we consider when using AI in supply chain?",
"What are the limitations of AI in robotics?",
"What are the long-term implications of AI on agriculture?",
"What are the long-term implications of AI on customer service?",
"What role does AI play in customer experience today?",
"How does AI compare to traditional methods in cybersecurity?",
"How is AI transforming education?",
"How can AI be used to solve problems in space exploration?",
"What innovations in AI could revolutionize education?",
"How does AI impact human decision-making in mental health?",
"How will AI shape the future of customer service?",
"How does AI interact with other technologies in human augmentation?",
"What challenges do researchers face when applying AI to predictive analytics?",
"What ethical dilemmas arise from AI in mental health?",
"How does AI impact human decision-making in creativity?",
"What are some misconceptions about AI in healthcare?",
"How is AI transforming retail?",
"What innovations in AI could revolutionize predictive analytics?",
"How is AI transforming energy efficiency?",
"What are the limitations of AI in social media?",
"How can AI enhance productivity in space exploration?",
"What are some misconceptions about AI in public policy?",
"What ethical dilemmas arise from AI in customer service?",
"How do biases in AI models affect supply chain?",
"What are the long-term implications of AI on social media?",
"What innovations in AI could revolutionize autonomous systems?",
"How does AI affect employment in augmented reality?",
"What are some misconceptions about AI in self-driving cars?",
"How do biases in AI models affect space exploration?",
"How do biases in AI models affect manufacturing?",
"What are the long-term implications of AI on financial fraud detection?",
"How do biases in AI models affect social media?",
"What are the long-term implications of AI on public policy?",
"How does AI interact with other technologies in gaming?",
"What are the benefits and drawbacks of AI in retail?",
"How is AI transforming public policy?",
"What innovations in AI could revolutionize military?",
"What are the latest advancements in AI for agriculture?",
"How can AI be used to solve problems in customer experience?",
"How does AI affect employment in virtual reality?",
"How does AI compare to traditional methods in scientific research?",
"How does AI affect employment in mental health?",
"What challenges do researchers face when applying AI to robotics?",
"How will AI shape the future of artificial creativity?",
"What risks should we consider when using AI in future jobs?",
"How does AI interact with other technologies in disaster response?",
"How can AI enhance productivity in virtual reality?",
"How does AI interact with other technologies in military?",
"How does AI impact human decision-making in criminal justice?",
"How does AI interact with other technologies in customer experience?",
"What are the latest advancements in AI for energy efficiency?",
"How can AI be made more reliable for creativity?",
"What are the latest advancements in AI for ethics?",
"How is AI transforming social media?",
"What ethical dilemmas arise from AI in autonomous systems?",
"How can AI be made more reliable for manufacturing?",
"What innovations in AI could revolutionize gaming?",
"How does AI compare to traditional methods in drug discovery?",
"What are the benefits and drawbacks of AI in biotechnology?",
"What are the long-term implications of AI on virtual reality?",
"What are the limitations of AI in creativity?",
"How can AI be made more reliable for finance?",
"How does AI impact human decision-making in language processing?",
"How does AI interact with other technologies in financial fraud detection?",
"How do biases in AI models affect ethics?",
"How does AI compare to traditional methods in customer service?",
"What role does AI play in human augmentation today?",
"How can AI be used to solve problems in retail?",
"How does AI affect employment in retail?",
"How do biases in AI models affect marketing?",
"How can AI be used to solve problems in public policy?",
"What are the benefits and drawbacks of AI in mental health?",
"What challenges do researchers face when applying AI to scientific research?",
"What challenges do researchers face when applying AI to healthcare?",
"What are the limitations of AI in marketing?",
"How can AI be made more reliable for elderly care?",
"What are the limitations of AI in artificial creativity?",
"What risks should we consider when using AI in drug discovery?",
"How does AI interact with other technologies in artificial creativity?",
"What are the benefits and drawbacks of AI in criminal justice?",
"How does AI compare to traditional methods in energy efficiency?",
"What challenges do researchers face when applying AI to transportation?",
"What ethical dilemmas arise from AI in gaming?",
"What innovations in AI could revolutionize customer service?",
"What are some misconceptions about AI in creativity?",
"What are the latest advancements in AI for artificial creativity?",
"How can AI enhance productivity in cybersecurity?",
"What challenges do researchers face when applying AI to customer experience?",
"What are the limitations of AI in public policy?",
"What ethical dilemmas arise from AI in biotechnology?",
"What challenges do researchers face when applying AI to blockchain?",
"How does AI affect employment in sports analytics?",
"How will AI shape the future of music composition?",
"What challenges do researchers face when applying AI to drug discovery?",
"How does AI impact human decision-making in ethics?",
"How do biases in AI models affect agriculture?",
"What ethical dilemmas arise from AI in healthcare?",
"How is AI transforming drug discovery?",
"What are some misconceptions about AI in business strategy?",
"What are the long-term implications of AI on creativity?",
"How does AI impact human decision-making in finance?",
"What role does AI play in education accessibility today?",
"How can AI be used to solve problems in education accessibility?",
"What challenges do researchers face when applying AI to sports analytics?",
"What challenges do researchers face when applying AI to gaming?",
"What innovations in AI could revolutionize financial fraud detection?",
"What are the latest advancements in AI for finance?",
"What are the long-term implications of AI on energy efficiency?",
"What risks should we consider when using AI in robotics?",
"How does AI impact human decision-making in space exploration?",
"How will AI shape the future of education?",
"How can AI be used to solve problems in scientific research?",
"What risks should we consider when using AI in climate change?",
"What risks should we consider when using AI in entertainment?",
"How will AI shape the future of language processing?",
"What ethical dilemmas arise from AI in augmented reality?",
"What innovations in AI could revolutionize augmented reality?",
"How can AI be used to solve problems in creativity?",
"What innovations in AI could revolutionize scientific research?",
"What role does AI play in education today?",
"How can AI be made more reliable for entertainment?",
"How do biases in AI models affect transportation?",
"How does AI impact human decision-making in virtual reality?",
"What challenges do researchers face when applying AI to future jobs?",
"How will AI shape the future of space exploration?",
"What innovations in AI could revolutionize supply chain?",
"How does AI compare to traditional methods in self-driving cars?",
"How does AI compare to traditional methods in disaster response?",
"How can AI be used to solve problems in mental health?",
"How can AI be used to solve problems in agriculture?",
"How does AI interact with other technologies in biotechnology?",
"How can AI be made more reliable for language processing?",
"What are the long-term implications of AI on retail?",
"What role does AI play in predictive analytics today?",
"What role does AI play in smart cities today?",
"What risks should we consider when using AI in education accessibility?",
"How do biases in AI models affect creativity?",
"What innovations in AI could revolutionize cybersecurity?",
"What role does AI play in sports analytics today?",
"What are the limitations of AI in personal assistants?",
"What are some misconceptions about AI in retail?",
"What are some misconceptions about AI in augmented reality?",
"What are the latest advancements in AI for education accessibility?",
"How is AI transforming space exploration?",
"What are the limitations of AI in customer experience?",
"How can AI be used to solve problems in future jobs?",
"How is AI transforming transportation?",
"What are the limitations of AI in retail?",
"How does AI impact human decision-making in education accessibility?",
"How does AI compare to traditional methods in customer experience?",
"What risks should we consider when using AI in healthcare?",
"What ethical dilemmas arise from AI in education accessibility?",
"What are the latest advancements in AI for blockchain?",
"What are some misconceptions about AI in predictive analytics?",
"What innovations in AI could revolutionize artificial creativity?",
"How can AI be made more reliable for customer service?",
"What challenges do researchers face when applying AI to music composition?",
"What are the benefits and drawbacks of AI in smart cities?",
"How does AI compare to traditional methods in sports analytics?",
"What role does AI play in disaster response today?",
"What role does AI play in autonomous systems today?",
"What are some misconceptions about AI in biotechnology?",
"What innovations in AI could revolutionize transportation?",
"How does AI impact human decision-making in law enforcement?",
"What risks should we consider when using AI in language processing?",
"How can AI be made more reliable for education accessibility?",
"What ethical dilemmas arise from AI in sports analytics?",
"What are the latest advancements in AI for biotechnology?",
"How does AI affect employment in entertainment?",
"How does AI compare to traditional methods in finance?",
"What challenges do researchers face when applying AI to military?",
"How can AI be used to solve problems in data privacy?",
"What innovations in AI could revolutionize climate change?",
"How is AI transforming data privacy?",
"What are some misconceptions about AI in agriculture?",
"How will AI shape the future of data privacy?",
"How does AI affect employment in education?",
"What ethical dilemmas arise from AI in future jobs?",
"How does AI interact with other technologies in cybersecurity?",
"What ethical dilemmas arise from AI in criminal justice?",
"How can AI enhance productivity in autonomous systems?",
"How will AI shape the future of energy efficiency?",
"What are the latest advancements in AI for scientific research?",
"What are the long-term implications of AI on entertainment?",
"How will AI shape the future of biotechnology?",
"How will AI shape the future of predictive analytics?",
"What role does AI play in military today?",
"What are some misconceptions about AI in customer service?",
"How does AI interact with other technologies in education?",
"How does AI impact human decision-making in robotics?",
"How can AI be made more reliable for education?",
"How does AI compare to traditional methods in healthcare?",
"What are the limitations of AI in energy efficiency?",
"How will AI shape the future of disaster response?",
"How do biases in AI models affect energy efficiency?",
"What ethical dilemmas arise from AI in personal assistants?",
"How can AI be used to solve problems in healthcare?",
"What are the limitations of AI in business strategy?",
"What are the limitations of AI in predictive analytics?",
"What ethical dilemmas arise from AI in language processing?",
"What are some misconceptions about AI in finance?",
"How does AI compare to traditional methods in augmented reality?",
"How can AI be made more reliable for mental health?",
"How does AI impact human decision-making in autonomous systems?",
"What are the latest advancements in AI for creativity?",
"How does AI compare to traditional methods in artificial creativity?",
"What are the benefits and drawbacks of AI in sports analytics?",
"What are the benefits and drawbacks of AI in future jobs?",
"What challenges do researchers face when applying AI to smart cities?",
"What are the latest advancements in AI for gaming?",
"What role does AI play in business strategy today?",
"How do biases in AI models affect law enforcement?",
"What are some misconceptions about AI in autonomous systems?",
"How will AI shape the future of autonomous systems?",
"What innovations in AI could revolutionize music composition?",
"What challenges do researchers face when applying AI to data privacy?",
"What challenges do researchers face when applying AI to news generation?",
"What are the limitations of AI in military?",
"How can AI be used to solve problems in smart cities?",
"How does AI impact human decision-making in transportation?",
"How does AI affect employment in cybersecurity?",
"What are the latest advancements in AI for personal assistants?",
"What challenges do researchers face when applying AI to criminal justice?",
"What role does AI play in drug discovery today?",
"What are the limitations of AI in healthcare?",
"How does AI impact human decision-making in education?",
"What ethical dilemmas arise from AI in cybersecurity?",
"What ethical dilemmas arise from AI in agriculture?",
"How will AI shape the future of law enforcement?",
"How does AI compare to traditional methods in language processing?",
"What are the limitations of AI in news generation?",
"What are the latest advancements in AI for criminal justice?",
"How can AI be used to solve problems in augmented reality?",
"What role does AI play in music composition today?",
"What are the benefits and drawbacks of AI in education?",
"How do biases in AI models affect predictive analytics?",
"What risks should we consider when using AI in energy efficiency?",
"How can AI be used to solve problems in robotics?",
"How does AI impact human decision-making in customer service?",
"How does AI interact with other technologies in elderly care?",
"What innovations in AI could revolutionize ethics?",
"What are the benefits and drawbacks of AI in ethics?",
"How can AI be made more reliable for public policy?",
"How is AI transforming predictive analytics?",
"What ethical dilemmas arise from AI in scientific research?",
"How does AI interact with other technologies in creativity?",
"What role does AI play in future jobs today?",
"How does AI compare to traditional methods in financial fraud detection?",
"How does AI impact human decision-making in sports analytics?",
"What are the long-term implications of AI on supply chain?",
"How will AI shape the future of blockchain?",
"How can AI enhance productivity in disaster response?",
"What ethical dilemmas arise from AI in social media?",
"How does AI affect employment in finance?",
"How will AI shape the future of manufacturing?",
"How can AI enhance productivity in healthcare?",
"How does AI impact human decision-making in news generation?",
"What innovations in AI could revolutionize virtual reality?",
"How does AI impact human decision-making in augmented reality?",
"How does AI impact human decision-making in music composition?",
"What risks should we consider when using AI in augmented reality?",
"How do biases in AI models affect climate change?",
"How does AI affect employment in news generation?",
"How can AI enhance productivity in finance?",
"What innovations in AI could revolutionize public policy?",
"What are the long-term implications of AI on personal assistants?",
"How does AI interact with other technologies in retail?",
"What are the long-term implications of AI on mental health?",
"What ethical dilemmas arise from AI in predictive analytics?",
"What innovations in AI could revolutionize mental health?",
"How does AI impact human decision-making in military?",
"What are the latest advancements in AI for marketing?",
"What are the benefits and drawbacks of AI in personal assistants?",
"What are some misconceptions about AI in supply chain?",
"How can AI be made more reliable for social media?",
"How can AI be made more reliable for future jobs?",
"What role does AI play in agriculture today?",
"What ethical dilemmas arise from AI in marketing?",
"How does AI interact with other technologies in mental health?",
"What role does AI play in public policy today?",
"What are the latest advancements in AI for entertainment?",
"How do biases in AI models affect sports analytics?",
"How can AI be made more reliable for ethics?",
"How does AI impact human decision-making in data privacy?",
"What are the long-term implications of AI on military?",
"How does AI interact with other technologies in transportation?",
"How is AI transforming military?",
"How does AI interact with other technologies in public policy?",
"How does AI compare to traditional methods in law enforcement?",
"How do biases in AI models affect biotechnology?",
"What are the limitations of AI in law enforcement?",
"What are the limitations of AI in biotechnology?",
"What are some misconceptions about AI in financial fraud detection?",
"How does AI affect employment in self-driving cars?",
"How does AI compare to traditional methods in transportation?",
"What ethical dilemmas arise from AI in energy efficiency?",
"What are the benefits and drawbacks of AI in gaming?",
"How do biases in AI models affect data privacy?",
"How does AI interact with other technologies in law enforcement?",
"What risks should we consider when using AI in space exploration?",
"How does AI impact human decision-making in supply chain?",
"What are the long-term implications of AI on ethics?",
"How can AI be used to solve problems in elderly care?",
"How can AI enhance productivity in news generation?",
"What ethical dilemmas arise from AI in business strategy?",
"How does AI compare to traditional methods in space exploration?",
"What challenges do researchers face when applying AI to business strategy?",
"What are the long-term implications of AI on education accessibility?",
"What are the long-term implications of AI on space exploration?",
"What risks should we consider when using AI in agriculture?",
"How does AI interact with other technologies in blockchain?",
"What are the long-term implications of AI on robotics?",
"How will AI shape the future of transportation?",
"How can AI be made more reliable for transportation?",
"How will AI shape the future of cybersecurity?",
"What are the benefits and drawbacks of AI in self-driving cars?",
"What are the benefits and drawbacks of AI in law enforcement?",
"What role does AI play in transportation today?",
"What are the benefits and drawbacks of AI in social media?",
"How can AI enhance productivity in business strategy?",
"What role does AI play in elderly care today?",
"What innovations in AI could revolutionize sports analytics?",
"How does AI interact with other technologies in ethics?",
"What are the benefits and drawbacks of AI in creativity?",
"What are the latest advancements in AI for customer experience?",
"What challenges do researchers face when applying AI to entertainment?",
"What role does AI play in blockchain today?",
"What are the long-term implications of AI on sports analytics?",
"What are some misconceptions about AI in personal assistants?",
"What are some misconceptions about AI in future jobs?",
"What risks should we consider when using AI in virtual reality?",
"What are the limitations of AI in drug discovery?",
"How will AI shape the future of virtual reality?",
"How do biases in AI models affect robotics?",
"How will AI shape the future of finance?",
"What are some misconceptions about AI in news generation?",
"What role does AI play in customer service today?",
"What are the latest advancements in AI for law enforcement?",
"What role does AI play in ethics today?",
"What are the long-term implications of AI on healthcare?",
"What risks should we consider when using AI in marketing?",
"What are the latest advancements in AI for supply chain?",
"What are the benefits and drawbacks of AI in human augmentation?",
"How does AI affect employment in customer service?",
"What innovations in AI could revolutionize education accessibility?",
"What innovations in AI could revolutionize social media?",
"How can AI enhance productivity in personal assistants?",
"How will AI shape the future of personal assistants?",
"What ethical dilemmas arise from AI in manufacturing?",
"How can AI enhance productivity in law enforcement?",
"What challenges do researchers face when applying AI to human augmentation?",
"How is AI transforming financial fraud detection?",
"How do biases in AI models affect language processing?",
"What are the long-term implications of AI on smart cities?",
"How will AI shape the future of elderly care?",
"How does AI affect employment in military?",
"How will AI shape the future of smart cities?",
"What are the limitations of AI in entertainment?",
"How is AI transforming human augmentation?",
"What are the long-term implications of AI on blockchain?",
"What challenges do researchers face when applying AI to space exploration?",
"How is AI transforming future jobs?",
"What are the long-term implications of AI on law enforcement?",
"What are the limitations of AI in criminal justice?",
"What risks should we consider when using AI in music composition?",
"What innovations in AI could revolutionize disaster response?",
"How can AI enhance productivity in education accessibility?",
"What are the benefits and drawbacks of AI in autonomous systems?",
"What are some misconceptions about AI in smart cities?",
"How can AI enhance productivity in elderly care?",
"How can AI enhance productivity in gaming?",
"How does AI impact human decision-making in entertainment?",
"How does AI compare to traditional methods in personal assistants?",
"How can AI be made more reliable for scientific research?",
"What innovations in AI could revolutionize blockchain?",
"What are the benefits and drawbacks of AI in blockchain?",
"What are the benefits and drawbacks of AI in finance?",
"How does AI affect employment in disaster response?",
"What are the benefits and drawbacks of AI in predictive analytics?",
"How can AI be used to solve problems in marketing?",
"How does AI interact with other technologies in drug discovery?",
"What are the limitations of AI in language processing?",
"How does AI impact human decision-making in public policy?",
"How can AI enhance productivity in sports analytics?",
"What are some misconceptions about AI in criminal justice?",
"What ethical dilemmas arise from AI in blockchain?",
"What innovations in AI could revolutionize news generation?",
"What are the long-term implications of AI on augmented reality?",
"What innovations in AI could revolutionize elderly care?",
"How does AI interact with other technologies in data privacy?",
"What are the limitations of AI in augmented reality?",
"What role does AI play in cybersecurity today?",
"What are the benefits and drawbacks of AI in space exploration?",
"What challenges do researchers face when applying AI to marketing?",
"What challenges do researchers face when applying AI to customer service?",
"What are the latest advancements in AI for sports analytics?",
"How is AI transforming customer service?",
"What are the long-term implications of AI on finance?",
"How does AI affect employment in social media?",
"How can AI be made more reliable for law enforcement?",
"What are the latest advancements in AI for manufacturing?",
"What ethical dilemmas arise from AI in transportation?",
"What ethical dilemmas arise from AI in financial fraud detection?",
"How does AI compare to traditional methods in blockchain?",
"How can AI be used to solve problems in gaming?",
"How does AI compare to traditional methods in social media?",
"What ethical dilemmas arise from AI in human augmentation?",
"What are the benefits and drawbacks of AI in education accessibility?",
"How is AI transforming language processing?",
"How will AI shape the future of financial fraud detection?",
"What are the limitations of AI in financial fraud detection?",
"How can AI enhance productivity in language processing?",
"How is AI transforming supply chain?",
"What are the benefits and drawbacks of AI in customer service?",
"What ethical dilemmas arise from AI in finance?",
"How do biases in AI models affect business strategy?",
"What are the latest advancements in AI for business strategy?",
"What ethical dilemmas arise from AI in military?",
"How can AI be used to solve problems in artificial creativity?",
"What role does AI play in criminal justice today?",
"How is AI transforming augmented reality?",
"What are the limitations of AI in disaster response?",
"How can AI be made more reliable for news generation?",
"What are the limitations of AI in education?",
"How can AI be made more reliable for biotechnology?",
"How does AI impact human decision-making in social media?",
"What are the latest advancements in AI for elderly care?",
"How do biases in AI models affect drug discovery?",
"How does AI compare to traditional methods in ethics?",
"What are the long-term implications of AI on data privacy?",
"What are the benefits and drawbacks of AI in climate change?",
"How does AI affect employment in supply chain?",
"How does AI impact human decision-making in energy efficiency?",
"How is AI transforming news generation?",
"What challenges do researchers face when applying AI to retail?",
"How is AI transforming blockchain?",
"How does AI affect employment in artificial creativity?",
"What are the benefits and drawbacks of AI in military?",
"What innovations in AI could revolutionize self-driving cars?",
"How can AI be used to solve problems in climate change?",
"How can AI be made more reliable for cybersecurity?",
"What role does AI play in personal assistants today?",
"How can AI enhance productivity in biotechnology?",
"What are the latest advancements in AI for space exploration?",
"How can AI enhance productivity in future jobs?",
"What risks should we consider when using AI in personal assistants?",
"How will AI shape the future of augmented reality?",
"What risks should we consider when using AI in education?",
"What are the latest advancements in AI for disaster response?",
"How do biases in AI models affect music composition?",
"How will AI shape the future of military?",
"How does AI compare to traditional methods in entertainment?",
"What are some misconceptions about AI in mental health?",
"How can AI be used to solve problems in predictive analytics?",
"How does AI affect employment in personal assistants?",
"How does AI impact human decision-making in biotechnology?",
"What role does AI play in social media today?",
"How will AI shape the future of ethics?",
"How does AI interact with other technologies in smart cities?",
"How can AI be used to solve problems in human augmentation?",
"What risks should we consider when using AI in disaster response?",
"What are some misconceptions about AI in artificial creativity?",
"What are the benefits and drawbacks of AI in agriculture?",
"How does AI impact human decision-making in predictive analytics?",
"How does AI impact human decision-making in gaming?",
"What are the limitations of AI in mental health?",
"What role does AI play in gaming today?",
"How does AI compare to traditional methods in autonomous systems?",
"What are the long-term implications of AI on disaster response?",
"How does AI interact with other technologies in news generation?",
"How can AI enhance productivity in robotics?",
"How can AI be made more reliable for retail?",
"What are the long-term implications of AI on climate change?",
"What are the latest advancements in AI for financial fraud detection?",
"How do biases in AI models affect education?",
"How is AI transforming music composition?",
"How is AI transforming business strategy?",
"What are the long-term implications of AI on education?",
"What challenges do researchers face when applying AI to manufacturing?",
"How do biases in AI models affect public policy?",
"How do biases in AI models affect disaster response?",
"What innovations in AI could revolutionize language processing?",
"How does AI interact with other technologies in manufacturing?",
"What are some misconceptions about AI in elderly care?",
"How can AI be made more reliable for sports analytics?",
"What innovations in AI could revolutionize future jobs?",
"What risks should we consider when using AI in self-driving cars?",
"How can AI enhance productivity in criminal justice?",
"How can AI enhance productivity in mental health?",
"How can AI be made more reliable for climate change?",
"What risks should we consider when using AI in ethics?",
"How does AI interact with other technologies in energy efficiency?",
"How do biases in AI models affect self-driving cars?",
"What are the benefits and drawbacks of AI in disaster response?",
"How will AI shape the future of human augmentation?",
"How can AI be used to solve problems in transportation?",
"What ethical dilemmas arise from AI in robotics?",
"How will AI shape the future of healthcare?",
"What risks should we consider when using AI in biotechnology?",
"How will AI shape the future of agriculture?",
"What challenges do researchers face when applying AI to cybersecurity?",
"How can AI enhance productivity in transportation?",
"How can AI enhance productivity in financial fraud detection?",
"What are the limitations of AI in data privacy?",
"What are the latest advancements in AI for smart cities?",
"What ethical dilemmas arise from AI in supply chain?",
"How can AI be used to solve problems in ethics?",
"How does AI impact human decision-making in retail?",
"How can AI be used to solve problems in personal assistants?",
"What are the benefits and drawbacks of AI in virtual reality?",
"What are the long-term implications of AI on gaming?",
"What are the long-term implications of AI on criminal justice?",
"What role does AI play in artificial creativity today?",
"What are the benefits and drawbacks of AI in manufacturing?",
"What risks should we consider when using AI in mental health?",
"How will AI shape the future of creativity?",
"What innovations in AI could revolutionize healthcare?",
"How does AI interact with other technologies in scientific research?",
"What are the limitations of AI in manufacturing?",
"What are the latest advancements in AI for virtual reality?",
"How can AI be made more reliable for military?",
"How does AI impact human decision-making in marketing?",
"What are the latest advancements in AI for robotics?",
"How does AI interact with other technologies in finance?",
"How does AI impact human decision-making in self-driving cars?",
"How can AI be used to solve problems in autonomous systems?",
"How can AI enhance productivity in predictive analytics?",
"What are some misconceptions about AI in cybersecurity?",
"What are some misconceptions about AI in climate change?",
"How can AI be used to solve problems in cybersecurity?",
"How does AI affect employment in transportation?",
"How can AI be used to solve problems in financial fraud detection?",
"What are the benefits and drawbacks of AI in drug discovery?",
"How is AI transforming biotechnology?",
"What risks should we consider when using AI in public policy?",
"What are the benefits and drawbacks of AI in healthcare?",
"How do biases in AI models affect elderly care?",
"How is AI transforming disaster response?",
"What innovations in AI could revolutionize creativity?",
"What role does AI play in entertainment today?",
"What risks should we consider when using AI in predictive analytics?",
"How do biases in AI models affect artificial creativity?",
"What risks should we consider when using AI in business strategy?",
"What are the long-term implications of AI on business strategy?",
"What ethical dilemmas arise from AI in climate change?",
"How can AI be used to solve problems in entertainment?",
"How does AI compare to traditional methods in mental health?",
"What role does AI play in energy efficiency today?",
"How does AI affect employment in marketing?",
"What challenges do researchers face when applying AI to climate change?",
"How can AI be used to solve problems in law enforcement?",
"What role does AI play in manufacturing today?",
"How does AI affect employment in scientific research?",
"How do biases in AI models affect education accessibility?",
"What are the latest advancements in AI for augmented reality?",
"How does AI impact human decision-making in smart cities?",
"How can AI enhance productivity in supply chain?",
"How does AI impact human decision-making in agriculture?",
"How can AI enhance productivity in self-driving cars?",
"How does AI affect employment in predictive analytics?",
"How can AI enhance productivity in military?",
"What innovations in AI could revolutionize smart cities?",
"How does AI impact human decision-making in cybersecurity?",
"How will AI shape the future of drug discovery?",
"What role does AI play in news generation today?",
"How does AI interact with other technologies in robotics?",
"How does AI affect employment in manufacturing?",
"How can AI be used to solve problems in music composition?",
"How can AI enhance productivity in climate change?",
"How do biases in AI models affect finance?",
"How is AI transforming agriculture?",
"How is AI transforming cybersecurity?",
"What innovations in AI could revolutionize retail?",
"How does AI interact with other technologies in music composition?",
"What innovations in AI could revolutionize robotics?",
"How does AI affect employment in space exploration?",
"What are some misconceptions about AI in drug discovery?",
"What are the latest advancements in AI for healthcare?",
"What innovations in AI could revolutionize business strategy?",
"What are the limitations of AI in virtual reality?",
"What are the limitations of AI in education accessibility?",
"How can AI be used to solve problems in language processing?",
"What ethical dilemmas arise from AI in virtual reality?",
"How does AI interact with other technologies in personal assistants?",
"What challenges do researchers face when applying AI to elderly care?",
"What risks should we consider when using AI in transportation?",
"How does AI interact with other technologies in criminal justice?",
"How will AI shape the future of future jobs?",
"What are some misconceptions about AI in military?",
"How will AI shape the future of climate change?",
"How does AI compare to traditional methods in news generation?",
"What ethical dilemmas arise from AI in space exploration?",
"How does AI impact human decision-making in healthcare?",
"What are some misconceptions about AI in customer experience?",
"How can AI enhance productivity in marketing?",
"How does AI compare to traditional methods in retail?",
"What challenges do researchers face when applying AI to mental health?",
"What are the long-term implications of AI on self-driving cars?",
"What challenges do researchers face when applying AI to financial fraud detection?",
"How do biases in AI models affect customer experience?",
"How does AI impact human decision-making in future jobs?",
"What are the limitations of AI in cybersecurity?",
"What role does AI play in space exploration today?",
"What challenges do researchers face when applying AI to augmented reality?",
"What are the benefits and drawbacks of AI in financial fraud detection?",
"How does AI impact human decision-making in elderly care?",
"How can AI enhance productivity in customer service?",
"How does AI affect employment in drug discovery?",
"How does AI interact with other technologies in social media?",
"What role does AI play in scientific research today?",
"What are the benefits and drawbacks of AI in customer experience?",
"How can AI be made more reliable for robotics?",
"What innovations in AI could revolutionize drug discovery?",
"What are some misconceptions about AI in gaming?",
"How does AI impact human decision-making in human augmentation?",
"What are some misconceptions about AI in blockchain?",
"What challenges do researchers face when applying AI to public policy?",
"What risks should we consider when using AI in gaming?",
"How does AI affect employment in gaming?",
"What are the benefits and drawbacks of AI in scientific research?",
"How does AI compare to traditional methods in predictive analytics?",
"How is AI transforming law enforcement?",
"What are the limitations of AI in space exploration?",
"What ethical dilemmas arise from AI in disaster response?",
"How can AI enhance productivity in public policy?",
"What are the benefits and drawbacks of AI in artificial creativity?",
"What risks should we consider when using AI in human augmentation?",
"How does AI compare to traditional methods in gaming?",
"What are some misconceptions about AI in virtual reality?",
"How can AI be made more reliable for virtual reality?",
"How does AI compare to traditional methods in human augmentation?",
"How can AI be used to solve problems in news generation?",
"How do biases in AI models affect smart cities?",
"How does AI interact with other technologies in business strategy?",
"What challenges do researchers face when applying AI to autonomous systems?",
"What are the limitations of AI in music composition?",
"How does AI affect employment in language processing?",
"What are the benefits and drawbacks of AI in entertainment?",
"How is AI transforming healthcare?",
"How is AI transforming climate change?",
"What challenges do researchers face when applying AI to social media?",
"How does AI affect employment in human augmentation?",
"What are the latest advancements in AI for data privacy?",
"How can AI be used to solve problems in criminal justice?",
"How does AI compare to traditional methods in climate change?",
"What are some misconceptions about AI in manufacturing?",
"How will AI shape the future of entertainment?",
"What role does AI play in augmented reality today?",
"What innovations in AI could revolutionize entertainment?",
"How does AI compare to traditional methods in education?",
"What are the long-term implications of AI on cybersecurity?",
"How can AI be made more reliable for human augmentation?",
"How is AI transforming autonomous systems?",
"What are the long-term implications of AI on scientific research?",
"How does AI compare to traditional methods in elderly care?",
"How can AI enhance productivity in blockchain?",
"How is AI transforming criminal justice?",
"What risks should we consider when using AI in retail?",
"How does AI affect employment in blockchain?",
"What are the benefits and drawbacks of AI in supply chain?",
"How does AI impact human decision-making in business strategy?",
"How can AI be used to solve problems in energy efficiency?",
"What innovations in AI could revolutionize personal assistants?",
"How does AI impact human decision-making in customer experience?",
"How does AI affect employment in energy efficiency?",
"What are the benefits and drawbacks of AI in business strategy?",
"How does AI compare to traditional methods in military?",
"What challenges do researchers face when applying AI to agriculture?",
"What are some misconceptions about AI in ethics?",
"What are the limitations of AI in sports analytics?",
"What are the long-term implications of AI on autonomous systems?",
"How is AI transforming creativity?",
"What are the long-term implications of AI on biotechnology?",
"What are the latest advancements in AI for future jobs?",
"How is AI transforming virtual reality?",
"How can AI be used to solve problems in sports analytics?",
"How does AI interact with other technologies in language processing?",
"How does AI compare to traditional methods in marketing?",
"How does AI interact with other technologies in education accessibility?",
"What are some misconceptions about AI in education?",
"How do biases in AI models affect scientific research?",
"How does AI compare to traditional methods in smart cities?",
"How can AI be used to solve problems in finance?",
"How can AI enhance productivity in ethics?",
"What are the limitations of AI in blockchain?",
"What risks should we consider when using AI in law enforcement?",
"How do biases in AI models affect autonomous systems?",
"What are the benefits and drawbacks of AI in augmented reality?",
"What are some misconceptions about AI in transportation?",
"What are the long-term implications of AI on drug discovery?",
"What ethical dilemmas arise from AI in news generation?",
"What role does AI play in language processing today?",
"How does AI affect employment in customer experience?",
"How do biases in AI models affect personal assistants?",
"How will AI shape the future of sports analytics?",
"How does AI impact human decision-making in climate change?",
"How do biases in AI models affect healthcare?",
"How can AI be made more reliable for customer experience?",
"What are the long-term implications of AI on marketing?",
"How does AI interact with other technologies in predictive analytics?",
"What role does AI play in financial fraud detection today?",
"How does AI affect employment in ethics?",
"What innovations in AI could revolutionize manufacturing?",
"How will AI shape the future of business strategy?",
"How will AI shape the future of public policy?",
"How do biases in AI models affect augmented reality?",
"How does AI affect employment in creativity?",
"What risks should we consider when using AI in blockchain?",
"How can AI be made more reliable for agriculture?",
"What role does AI play in healthcare today?",
"How does AI interact with other technologies in sports analytics?",
"How will AI shape the future of retail?",
"How can AI be made more reliable for business strategy?",
"How can AI be used to solve problems in manufacturing?",
"What role does AI play in retail today?",
"What are the limitations of AI in gaming?",
"What are the latest advancements in AI for language processing?",
"What ethical dilemmas arise from AI in artificial creativity?",
"What are the long-term implications of AI on customer experience?",
"What role does AI play in mental health today?",
"What innovations in AI could revolutionize agriculture?",
"How does AI impact human decision-making in personal assistants?",
"What ethical dilemmas arise from AI in elderly care?",
"How can AI enhance productivity in creativity?",
"How does AI affect employment in smart cities?",
"What ethical dilemmas arise from AI in education?",
"How is AI transforming smart cities?",
"What are the limitations of AI in agriculture?",
"What are the benefits and drawbacks of AI in elderly care?",
"What are the limitations of AI in human augmentation?",
"How can AI be made more reliable for smart cities?",
"What are the limitations of AI in finance?",
"How do biases in AI models affect military?",
"How does AI affect employment in law enforcement?",
"How does AI affect employment in healthcare?",
"How does AI affect employment in agriculture?",
"How does AI compare to traditional methods in business strategy?",
"How can AI be made more reliable for artificial creativity?",
"What are the long-term implications of AI on future jobs?",
"What risks should we consider when using AI in military?",
"How can AI enhance productivity in scientific research?",
"How can AI enhance productivity in music composition?",
"What role does AI play in finance today?",
"How will AI shape the future of gaming?",
"How does AI affect employment in data privacy?",
"What are some misconceptions about AI in language processing?",
"How does AI impact human decision-making in blockchain?",
"How do biases in AI models affect customer service?",
"How does AI affect employment in elderly care?",
"What are the benefits and drawbacks of AI in news generation?",
"How will AI shape the future of customer experience?",
"What are the limitations of AI in smart cities?",
"How does AI compare to traditional methods in virtual reality?",
"What are the long-term implications of AI on predictive analytics?",
"What ethical dilemmas arise from AI in ethics?",
"How does AI compare to traditional methods in music composition?",
"How can AI enhance productivity in energy efficiency?",
"What are some misconceptions about AI in social media?",
"How can AI be made more reliable for marketing?",
"What innovations in AI could revolutionize human augmentation?",
"What role does AI play in creativity today?",
"How does AI compare to traditional methods in data privacy?",
"What are the benefits and drawbacks of AI in language processing?",
"What role does AI play in self-driving cars today?",
"What challenges do researchers face when applying AI to energy efficiency?",
"How will AI shape the future of robotics?",
"What are some misconceptions about AI in music composition?",
"What innovations in AI could revolutionize data privacy?",
"What are the benefits and drawbacks of AI in data privacy?",
"How can AI enhance productivity in entertainment?",
"What are some misconceptions about AI in marketing?",
"How can AI be made more reliable for healthcare?",
"How can AI be made more reliable for augmented reality?",
"How does AI interact with other technologies in augmented reality?",
"How can AI be used to solve problems in biotechnology?",
"How does AI impact human decision-making in drug discovery?",
"How can AI enhance productivity in smart cities?",
"How do biases in AI models affect future jobs?",
"How does AI affect employment in public policy?",
"What innovations in AI could revolutionize law enforcement?",
"What are the limitations of AI in autonomous systems?",
"What risks should we consider when using AI in cybersecurity?",
"What role does AI play in virtual reality today?",
"What risks should we consider when using AI in scientific research?",
"How does AI interact with other technologies in self-driving cars?",
"What role does AI play in marketing today?",
"What challenges do researchers face when applying AI to artificial creativity?",
"What are some misconceptions about AI in robotics?",
"How does AI compare to traditional methods in biotechnology?",
"How can AI be used to solve problems in business strategy?",
"How do biases in AI models affect virtual reality?",
"How can AI be made more reliable for energy efficiency?",
"What innovations in AI could revolutionize finance?",
"How can AI enhance productivity in social media?",
"What risks should we consider when using AI in autonomous systems?",
"What risks should we consider when using AI in finance?",
"What risks should we consider when using AI in data privacy?",
"What ethical dilemmas arise from AI in entertainment?",
"How can AI be used to solve problems in drug discovery?",
"What are the latest advancements in AI for news generation?",
"How can AI be made more reliable for gaming?",
"How can AI enhance productivity in manufacturing?",
"What are the latest advancements in AI for music composition?",
"How is AI transforming mental health?",
"How does AI affect employment in criminal justice?",
"How does AI interact with other technologies in customer service?",
"What risks should we consider when using AI in financial fraud detection?",
"How can AI be used to solve problems in disaster response?",
"How to manage tasks in no-code apps?"
]

def chat_with_ai(api_key: str, question: str) -> str:
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }

    messages = [
        {"role": "user", "content": question}
    ]

    data = {
        "model": MODEL,
        "messages": messages,
        "temperature": 0.7
    }

    for attempt in range(MAX_RETRIES):
        try:
            logging.info(f"Attempt {attempt+1} for question: {question[:50]}...")
            response = requests.post(
                f"{BASE_URL}/v1/chat/completions",
                headers=headers,
                json=data,
                timeout=30
            )

            if response.status_code == 200:
                return response.json()["choices"][0]["message"]["content"]

            logging.warning(f"API Error ({response.status_code}): {response.text}")
            time.sleep(RETRY_DELAY)

        except Exception as e:
            logging.error(f"Request failed: {str(e)}")
            time.sleep(RETRY_DELAY)

    raise Exception("Max retries exceeded")

def run_bot(api_key: str):
    while True:  # Outer loop to repeat the questions indefinitely
        random.shuffle(QUESTIONS)
        logging.info(f"Starting chatbot with {len(QUESTIONS)} questions in random order")

        for i, question in enumerate(QUESTIONS, 1):
            logging.info(f"\nProcessing question {i}/{len(QUESTIONS)}")
            logging.info(f"Question: {question}")

            start_time = time.time()
            try:
                response = chat_with_ai(api_key, question)
                elapsed = time.time() - start_time

                # Print the entire response
                print(f"Answer to '{question[:50]}...':\n{response}")

                logging.info(f"Received full response in {elapsed:.2f}s")
                logging.info(f"Response length: {len(response)} characters")

                # Ensure the script waits for the full response before proceeding
                time.sleep(QUESTION_DELAY)  # Wait before asking next question

            except Exception as e:
                logging.error(f"Failed to process question: {str(e)}")
                continue

def main():
    print("Title: GaiaAI Chatbot")
    print("Twitter: https://twitter.com/abe_sten")
    api_key = input("Enter your API key: ")
    run_bot(api_key)

if __name__ == "__main__":
    main()
